investment_data_products:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: target/warehouse.duckdb
      extensions:
        - httpfs
        - iceberg
      settings:
        unsafe_enable_version_guessing: true
      secrets:
        - type: s3
          region: "{{ env_var('AWS_REGION') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      plugins:
        - module: investment_data_products.dbt_plugins.iceberg_store
      threads: 4
